# Configuration options can be accessed as
#   configatron.site_name

development: &local
    site_name: RubyGrade
    site_url: http://rubygrade.heroku.com
    
    company_name: BaseApp LTDA
    admin_email: admin@user.com
    
    support_name: Support
    support_email: contact@user.com

production:
  <<: *local
  
staging:
  <<: *local

test:
  <<: *local
